name: CI Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
      
env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.408'
        
      - name: Restore Dependencies
        run: dotnet restore 
      
      - name: Build
        run: dotnet build --no-restore -c Release
      
      - name: Test
        run: dotnet test --no-build -c Release
  
  docker-publish:
    needs: build-and-test
    runs-on: ubuntu-22.04
    
    permissions:
      contents: read
      packages: write
  
    strategy:
      fail-fast: false
      matrix: 
        include:
          - service-name: aggregator
            dockerfile: Dockerfile
          - service-name: user-profile
            dockerfile: ./Services/UserProfileService/Dockerfile
          - service-name: event-catalog
            dockerfile: ./Services/EventCatalogService/Dockerfile
          - service-name: venue-service
            dockerfile: ./Services/EventManagmentSystem/Dockerfile
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Log in to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Metadata
        uses: docker/metadata-action@v5
        with: 
          images: ${{ env.REGISRTY }}/${{ env.IMAGE_NAME }}/${{ matrix.service-name }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,format=long
            type=ref,event=branch
      
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        